namespace Dash.Types
{
    public enum EventType
    {
        Undefined = 0,

        // Core
        WorldInitialize,
        WorldDispose,
        BackgroundCreate,
        TileCreate,
        LeaveGamePlaySceneContext,

        // Service
        ServiceReady,
        ChangeMonies,
        ReceiveTalentTimeReward,
        OpenBox,
        OpenBoxDataChanged,
        OnGachaOpen,
        OnGachaTimeEnd,
        LevelUpEquipment,
        LevelupAbility,
        UpgradeCharacter,
        OnChangeCharacter,
        OnPreviewCharacter,
        OnPreviewWeapon,
        OnPreviewArmor,
        OnChangeSkill,
        OnChangeEpisode,
        OnCombineEquipment,
        SetNicknameResult,
        OtherPlayerInfo,
        SearchPlayerNickname,
        OnAccountReset,
        OnCompleteEpGroupMission,
        OnCompleteMission,
        OnUseViewCharacter,
        OnProgressChanged,
        OnGetCompletedMissions,
        OnReceiveMissionsReward,
        OnReceiveConquestTierReward,
        OnReceiveConquestSeasonReward,
        OnWorldMissionRankingReward,
        OnWorldMissionScoreReward,
        OnWorldMissionCoopReward,
        OnEpisodeEntyrCount,
        OnSetDisplayCharacter,
        //SeasonPass
        OnSeasonPassReceive,

        //Character
        UpdateUsingCharacter,
        OnCharacterUnLockComplete,
        OnCharacterExpUpComplete,
        OnCharacterOvercomeUpComplete,
        OnCharacterRankUpComplete,
        OnCharacterRuneUnlock,
        OnCharacterRefresh,

        UpdateEquipmentSlot,
        UpdateSkill,
        CheckMatch,
        CheckArena,
        ForgiveArena,
        OnPurchase,
        OnProductList,
        OnProductInited,
        UnrewardedMissions,
        StartAutoMatch,
        CancelAutoMatch,
        LeavePartyByBackButton,
        LeaveParty,
        RefreshDeckPartyPage,
        //Entry
        LoadingComplete,

        //Setting
        OnCouponUse,

        //HIve
        OnHiveConnectChanged,
        OnHiveDelete,

        // Quest
        ResetDailyQeust,

        //Mail
        OnListMail,
        OnReadMail,
        OnReceiveMail,
        OnReadReceiveAllMail,
        OnChangeMailCount,

        // Billing
        OnIAPInitialized,
        OnIAPPurchaseSucceed,
        OnIAPPurchaseFailed,
        OnIAPConfirmPurchase,

        OnBuyTriggerPackage,

        // MobileAds
        OnRewardedAdLoaded,
        OnRewardedAdFailedToLoad,
        OnRewardedAdOpening,
        OnRewardedAdFailedToShow,
        OnRewardedAdUserEarnedReward,
        OnRewardedAdClosed,

        OnAdsRewarded,

        // Equip
        UnEquipItem,
        OnUnEquipItem,
        ChangeEquipItem,
        OnChangedEquipItem,
        ChangeEquipRune,
        OnChangedEquipRune,
        OnEquipmentDecomposeComplete,
        OnWeaponOvercomeUpComplete,
        OnWeaponReforgeUpComplete,

        OnResetComplete,

        // Item
        OnEquipmentExpUp,
        OnRewardBoxUseComplete,
        OnEquipmentToggleLock,
        OnShowWeaponGrowthView,
        OnEquipmentRefresh,
        OnEventExchangeComplete,
        OnExchangeComplete,
        // LobbyEvent
        OnRewardEvent,
        OnRewardEventGacha,
        OnRewardLotteryEvent,
        OnGetEventReward,
        OnReceiveTimeResourceReward,
        //Chat
        OnPartyChatMessage,
        OnFriendChat,

        // Multiplay
        ServerConnectResult,
        SessionClosed,
        LoginResult,
        OtherSessionClosed,
        OnEnqueueMatch,
        OnDequeueMatch,
        OnMatchTimeOut,
        ReturnToLobby,
        OnStartMatch,
        NoticeEnqueue,
        RecruitPartyMessage,
        //Party
        OnCreateParty,
        OnJoinParty,
        OnLeaveParty,
        OnLeavePartyMainPopup,
        OnPartyReady,
        RefreshPartyInfo,
        RefreshPartyMemberInGameStatus,
        PartyMemberUpdateUsingCharacter,
        PartyMemberUpdateEquipmentSlot,
        PartyMemberUpdateSkill,
        PartyMemberOnline,
        PartyMemberInfoUpdate,
        OnSetPartyTimer,
        OnCancelPartyTimer,
        OnPartyInvite,
        OnPartyInviteRefuse,
        OnChangeInviteAuthority,

        // Event
        OnClickEventButton,

        // Conquest
        OnConquestSeasonChanged,
        SetConquestScoreInfo,

        //WorldMission
        SetWorldMissionScoreInfo,

        // Game Play
        ApplyJoystickPosition,
        ActionState,
        ActionInvoke,
        ActorSummon,
        ActorIntro,
        ActorDead,
        ActorEffect,
        ActorRevive,
        ActorRemove,
        ActorRunaway,
        AngelCreated,
        AngelRemove,
        AttachActorObject,
        AttachBuff,
        AreaCreated,
        AreaAdditionalEffectBase,
        AreaDestroy,
        AreaHit,
        ArenaReward,
        AuthorityChanged,
        AddBossTotalHpTarget,
        AddReconnectingPlayer,
        BarrierCreated,
        BarrierDestroyed,
        BossTotalHpInit,
        CharacterSummon,
        CharacterInit,
        CharacterDead,
        EpisodeChanged,
        ChangeModelScale,
        ChangeGroggyPoint,
        ChangeGroggyState,
        ChangeUserPlayer,
        ChangeDeck,
        CoopReviveProcessing,
        CoopRevivePending,
        CreateItem,
        CloseGroggyState,
        DainnSoulExplosionAttach,
        DevilCreated,
        DetachBuff,
        DummyEffectBase,
        DummyDestroy,
        EndArena,
        EntityAdded,
        EntityRemoved,
        EnterGroggyState,
        EventActionInvoke,
        SkillChanged,
        SkillConditionChanged,
        SkillChargeGaugeChanged,
        SkillDurationGaugeChanged,
        SkillUltGaugeChanged,
        SkillStackChanged,
        SkillActiveChanged,

        SkillInvoke,
        UltSkillInvoke,
        SiegHitCounterAttackAddDamage,
        SiegHitCounterAttackStart,
        GamePlaySceneEntered,
        GamePaused,
        GameResumed,
        GameResult,
        WorldMissionGameResult,
        GameOverCountDownStart,
        TilePortal,
        GainDropped,
        GoldDropped,
        GotDamage,
        HpChange,
        Heal,
        HitFreeze,
        InvokeStageEvent,
        ItemDropped,
        MaxHpChanged,
        MyCharacterInit,
        NetworkStatusWarning,
        NetworkStatusError,
        NetworkStatusFine,
        ReconnectSingleArena,
        OpenGroggyState,
        Ping,
        PlayerStatusChanged,
        PlayerDropped,
        ProjectileAdditionalEffectBase,
        ProjectileReflect,
        ProjectilePierce,
        ProjectileHit,
        ProjectileCreated,
        ProjectileDestroy,
        PreloadStageEffect,
        GoldChestCreated,
        GoldChestRemove,
        GeneratorCreated,
        GeneratorDestroy,
        RewardChestCreated,
        RemoveItem,
        RemoveReconnectingPlayer,
        StartArena,
        StageLoading,
        StageLoaded,
        StageReady,
        StageWave,
        StageEventDone,
        SectorChanged,
        StageClear,
        LastStageClear,
        ShowEmoticon,
        SetInputEnable,
        SelectAngelChoice,
        SelectDevilChoice,
        WaitingSkillSelectAdded,
        WaitReconnectingPlayers,
        WeaponInit,
        Shapeshift,
        ReconnectAllDone,
        PauseGame,
        PausePanelShow,
        IncreaseProtectionCount,

        //UI???? ???? ????????
        OnSelectCharacterButtonDown,
        OnSortInventoryItemButtonDown,
        OnShowCombineEquipmentPopup,
        ShowSelectEquipmentSlotPanel,
        CloseSelectEquipmentSlotPanel,
        SelectCombineItem,
        OnInventoryItemChanged,
        OnEquipmentDataChanged,
        OnGainNewCharacter,
        OnCollectionChanged,
        OnCharacterSoulsChanged,
        OnPopupClosedAll,
        OnPopupShow,
        OnShowReopenPopupButton,
        OnScreenEffectFadeIn,
        OnChangeWorldPageContext,
        RequestAddFriend,
        RefreshFriendBadge,
        OnEpisodeSelected,
        OnItemFilterChanged,
        OnChangeTopInfo,
        //Tutorial
        OnInitLobbyTutorial,
        OnActiveLobbyTutorial,
        OnCompleteLobbyTutorial,
        //Friend
        OnFriendInfo,
        OnFriendAccept,
        OnFriendRemove,
        OnFriendOnline,

        //Editor Tool
        OnEditorToolPlayAction,
    }
}