// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Account : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return OidAccount > 0;
        }

        public Account() { }
        public Account(Account other)
        {
            OidAccount = other.OidAccount;
            Country = other.Country;
            Created = other.Created;
            DisplayCharacterId = other.DisplayCharacterId;
            Exp = other.Exp;
            LatestLogon = other.LatestLogon;
            Level = other.Level;
            Nickname = other.Nickname;
            ReturnTime = other.ReturnTime;
            Tester = other.Tester;
            TimeOffset = other.TimeOffset;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public int Level { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public int Exp { get; set; }
        [MessagePack.Key(7)]
        [Column]
        public string Nickname { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public string Country { get; set; }
        [MessagePack.Key(10)]
        [Column]
        public sbyte TimeOffset { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public DateTime Created { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public DateTime LatestLogon { get; set; }
        [MessagePack.Key(8)]
        [Column]
        public DateTime? ReturnTime { get; set; }
        [MessagePack.Key(9)]
        [Column]
        public bool Tester { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public int DisplayCharacterId { get; set; }
    }
}
