// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Auth : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(AuthType)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { AuthType.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Auth() { }
        public Auth(Auth other)
        {
            OidAccount = other.OidAccount;
            AuthType = other.AuthType;
            AuthId = other.AuthId;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public byte AuthType { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public string AuthId { get; set; }
    }
}
