// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Character : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Id)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Id.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Character() { }
        public Character(Character other)
        {
            OidAccount = other.OidAccount;
            Id = other.Id;
            Exp = other.Exp;
            Level = other.Level;
            Overcome = other.Overcome;
            Rank = other.Rank;
            RuneTier = other.RuneTier;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public int Id { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public byte Level { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public uint Exp { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public byte Overcome { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public byte Rank { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public byte RuneTier { get; set; }
    }
}
