// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Collection : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Id)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Id.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Collection() { }
        public Collection(Collection other)
        {
            OidAccount = other.OidAccount;
            Id = other.Id;
            Param1 = other.Param1;
            Param2 = other.Param2;
            Param3 = other.Param3;
            Param4 = other.Param4;
            Param5 = other.Param5;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public int Id { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public sbyte? Param1 { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public sbyte? Param2 { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public sbyte? Param3 { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public sbyte? Param4 { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public sbyte? Param5 { get; set; }
    }
}
