// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class CompletedMission : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(MissionId)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { MissionId.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public CompletedMission() { }
        public CompletedMission(CompletedMission other)
        {
            OidAccount = other.OidAccount;
            MissionId = other.MissionId;
            IsRewarded = other.IsRewarded;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public int MissionId { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public bool IsRewarded { get; set; }
    }
}
