// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class ConquestScore : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public ConquestScore() { }
        public ConquestScore(ConquestScore other)
        {
            OidAccount = other.OidAccount;
            BestTierId = other.BestTierId;
            Data = other.Data;
            IsSeasonRewarded = other.IsSeasonRewarded;
            RewardedTierId = other.RewardedTierId;
            Score = other.Score;
            SeasonId = other.SeasonId;
            UpdateTime = other.UpdateTime;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public int SeasonId { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public uint Score { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public bool IsSeasonRewarded { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public int RewardedTierId { get; set; }
        [MessagePack.Key(7)]
        [Column]
        public DateTime UpdateTime { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte[] Data { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public int BestTierId { get; set; }
    }
}
