// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class ConquestScoreRecord : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(SeasonId); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(OidAccount)}", keys[0]) };
        }

        public string GetMainKey() { return SeasonId.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { OidAccount.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public ConquestScoreRecord() { }
        public ConquestScoreRecord(ConquestScoreRecord other)
        {
            SeasonId = other.SeasonId;
            OidAccount = other.OidAccount;
            Data = other.Data;
            Rank = other.Rank;
            Score = other.Score;
            TierId = other.TierId;
            UpdateTime = other.UpdateTime;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public int SeasonId { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public uint Score { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public DateTime UpdateTime { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte[] Data { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public int Rank { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public int TierId { get; set; }
    }
}
