// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Coupon : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(Id); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return Id.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return Id > 0;
        }

        public Coupon() { }
        public Coupon(Coupon other)
        {
            Id = other.Id;
            Code = other.Code;
            Count = other.Count;
            Data = other.Data;
            DataCondition = other.DataCondition;
            End = other.End;
            Start = other.Start;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public uint Id { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public string Code { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public int Count { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public byte[] Data { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public byte[] DataCondition { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public DateTime Start { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public DateTime End { get; set; }
    }
}
