// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Deck : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Id)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Id.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Deck() { }
        public Deck(Deck other)
        {
            OidAccount = other.OidAccount;
            Id = other.Id;
            Ai1 = other.Ai1;
            Ai2 = other.Ai2;
            CharacterId = other.CharacterId;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public byte Id { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public int CharacterId { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public int Ai1 { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public int Ai2 { get; set; }
    }
}
