// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class EpisodeClear : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(EpisodeId)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { EpisodeId.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public EpisodeClear() { }
        public EpisodeClear(EpisodeClear other)
        {
            OidAccount = other.OidAccount;
            EpisodeId = other.EpisodeId;
            MissionBits = other.MissionBits;
            RewardedStar = other.RewardedStar;
            UpdateTime = other.UpdateTime;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public int EpisodeId { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte MissionBits { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public byte RewardedStar { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public DateTime? UpdateTime { get; set; }
    }
}
