// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Friend : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(OidFriend)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { OidFriend.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Friend() { }
        public Friend(Friend other)
        {
            OidAccount = other.OidAccount;
            OidFriend = other.OidFriend;
            CreateTime = other.CreateTime;
            InviteState = other.InviteState;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public ulong OidFriend { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public byte InviteState { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public DateTime CreateTime { get; set; }
    }
}
