// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class GachaHistory : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Id)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Id.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return Id > 0;
        }

        public GachaHistory() { }
        public GachaHistory(GachaHistory other)
        {
            OidAccount = other.OidAccount;
            Id = other.Id;
            ConvertedRewardData = other.ConvertedRewardData;
            GachaId = other.GachaId;
            Received = other.Received;
            RewardData = other.RewardData;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public ulong Id { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public int GachaId { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public DateTime Received { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public byte[] RewardData { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte[] ConvertedRewardData { get; set; }
    }
}
