// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class GameLog : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(Id); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Time)}", keys[0]) };
        }

        public string GetMainKey() { return Id.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Time.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return Id > 0;
        }

        public GameLog() { }
        public GameLog(GameLog other)
        {
            Id = other.Id;
            Time = other.Time;
            Command = other.Command;
            Country = other.Country;
            Level = other.Level;
            OidAccount = other.OidAccount;
            Payload = other.Payload;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public long Id { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public DateTime Time { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public int Level { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public string Country { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public string Command { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public string Payload { get; set; }
    }
}
