// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class GuildMember : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidGuild); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(OidAccount)}", keys[0]) };
        }

        public string GetMainKey() { return OidGuild.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { OidAccount.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public GuildMember() { }
        public GuildMember(GuildMember other)
        {
            OidGuild = other.OidGuild;
            OidAccount = other.OidAccount;
            Grade = other.Grade;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public int OidGuild { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte Grade { get; set; }
    }
}
