// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    public partial class HiveItem
    {
        public string TransactionId { get; set; }
        public string Id { get; set; }
        public string Data { get; set; }
    }
}
