// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class IapReceipt : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(TransactionId); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return TransactionId.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public IapReceipt() { }
        public IapReceipt(IapReceipt other)
        {
            TransactionId = other.TransactionId;
            Created = other.Created;
            OidAccount = other.OidAccount;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public string TransactionId { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public DateTime? Created { get; set; }
    }
}
