// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Mail : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Id)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Id.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return Id > 0;
        }

        public Mail() { }
        public Mail(Mail other)
        {
            OidAccount = other.OidAccount;
            Id = other.Id;
            AdminId = other.AdminId;
            Created = other.Created;
            Data = other.Data;
            Expire = other.Expire;
            Hidden = other.Hidden;
            Read = other.Read;
            Received = other.Received;
            Type = other.Type;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public ulong Id { get; set; }
        [MessagePack.Key(9)]
        [Column]
        public string Type { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public byte[] Data { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public DateTime Created { get; set; }
        [MessagePack.Key(7)]
        [Column]
        public DateTime? Read { get; set; }
        [MessagePack.Key(8)]
        [Column]
        public DateTime? Received { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public DateTime? Hidden { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public DateTime Expire { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public string AdminId { get; set; }
    }
}
