// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class MailTemplate : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(Id); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return Id.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return Id > 0;
        }

        public MailTemplate() { }
        public MailTemplate(MailTemplate other)
        {
            Id = other.Id;
            Data = other.Data;
            DataCondition = other.DataCondition;
            End = other.End;
            Expire = other.Expire;
            ExpireDays = other.ExpireDays;
            Start = other.Start;
            Target = other.Target;
            Type = other.Type;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public uint Id { get; set; }
        [MessagePack.Key(8)]
        [Column]
        public string Type { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public byte[] Data { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public byte[] DataCondition { get; set; }
        [MessagePack.Key(6)]
        [Column]
        public DateTime Start { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public DateTime End { get; set; }
        [MessagePack.Key(7)]
        [Column]
        public string Target { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public DateTime? Expire { get; set; }
        [MessagePack.Key(5)]
        [Column]
        public byte? ExpireDays { get; set; }
    }
}
