// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class Money : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(Type)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { Type.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public Money() { }
        public Money(Money other)
        {
            OidAccount = other.OidAccount;
            Type = other.Type;
            Free = other.Free;
            Paid = other.Paid;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public string Type { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public int Free { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public int Paid { get; set; }
    }
}
