// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    public partial class Retention
    {
        public ulong OidAccount { get; set; }
        public DateTime Date { get; set; }
        public DateTime DateTime { get; set; }
        public bool IsNew { get; set; }
        public string Country { get; set; }
        public int Level { get; set; }
        public bool R1 { get; set; }
        public bool R2 { get; set; }
        public bool R3 { get; set; }
        public bool R4 { get; set; }
        public bool R5 { get; set; }
        public bool R6 { get; set; }
        public bool R7 { get; set; }
        public bool R15 { get; set; }
        public bool R30 { get; set; }
    }
}
