// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class TimeResourceReward : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => false;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return null;
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return null;
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public TimeResourceReward() { }
        public TimeResourceReward(TimeResourceReward other)
        {
            OidAccount = other.OidAccount;
            ArmorExpChange = other.ArmorExpChange;
            CharExpChange = other.CharExpChange;
            RewardTime = other.RewardTime;
            WeaponExpChange = other.WeaponExpChange;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public int CharExpChange { get; set; }
        [MessagePack.Key(4)]
        [Column]
        public int WeaponExpChange { get; set; }
        [MessagePack.Key(1)]
        [Column]
        public int ArmorExpChange { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public DateTime RewardTime { get; set; }
    }
}
