// This code is generated by EntityTypeGenerator. Dot not Edit!
using System;
using System.Collections.Generic;

#nullable disable

namespace Dash.Model.Rdb
{
    [MessagePack.MessagePackObject()]
    public partial class TimeReward : Common.Model.IModel
    {
        public static bool IsMultipleDbModel => true;
        public static string GetMainKeyName() { return nameof(OidAccount); }
        public static List<KeyValuePair<string, object>> MakeSubKeysWithName(params object[] keys)
        {
            return new List<KeyValuePair<string, object>>() { new KeyValuePair<string, object>($"@{nameof(RewardType)}", keys[0]) };
        }

        public string GetMainKey() { return OidAccount.ToString(); }
        public List<string> GetSubKeys()
        {
            return new List<string>() { RewardType.ToString() };
        }
        public bool IsAutoIncKeysValid()
        {
            return true;
        }

        public TimeReward() { }
        public TimeReward(TimeReward other)
        {
            OidAccount = other.OidAccount;
            RewardType = other.RewardType;
            Count = other.Count;
            RewardTime = other.RewardTime;
        }


        [MessagePack.Key(0)]
        [Column]
        [KeyColumn]
        public ulong OidAccount { get; set; }
        [MessagePack.Key(1)]
        [Column]
        [KeyColumn]
        public string RewardType { get; set; }
        [MessagePack.Key(2)]
        [Column]
        public ushort Count { get; set; }
        [MessagePack.Key(3)]
        [Column]
        public DateTime RewardTime { get; set; }
    }
}
